name: Solar System Workflow 

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
jobs:
  unit-testing:
     name: Unit testing 
     runs-on: ubuntu-latest
     steps:
     - name: Checkout Repository
       uses: actions/checkout@v7.0.1

     - name: Set up nodejs version 
       uses: actions/setup-node@v7.0.0
       with:
          node-version: 18
     - name: Install dependencies
       run: npm  install

     - name: Unit testing
       run: npm test  

