name: solar system work flow

on:
  workflow_dispatch: 
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
jobs:
   unit-testing:
      name: unit testing
      strategy:
        matrix:
          nodejs_version: [19,20]
          operating_system: [ubuntu-latest,macos-latest]
          exclude:
            - nodejs_version: 19
              operating_system: macos_latest
      runs-on: ${{ matrix.operating_system }}
      steps:
      - name: check out repo
        uses: actions/checkout@v4
      - name: set up node js version - ${{ matrix.nodejs_version }}
        uses:  actions/setup-node@v3
        with:
          node-version: ${{matrix.nodejs_version}}
      - name: install dependencies
        run: npm install
      - name: Check Code Coverage
        continue-on-error: true
        run: npm run coverage
        
      - name: Archive Test Result-${{ matrix.nodejs_version }}-${{ strategy.job-total }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.run_id }}
          path: coverage
          retention-days: 2


    
      - name: unit testing
        run: npm test

      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-TestResult-${{ matrix.operating_system }}${{ strategy.job-index }}
          path: test-results.xml

                   # name: Mocha-TestResult-${{ matrix.operating_system }}-${{ strategy.job-index }}

