name: solar system work flow

on:
  workflow_dispatch: 
  push:
    branches:
      - main
      - 'feature/*'
jobs:
   unit-testing:
      name: unit testing
      runs-on: ubuntu-latest
      steps:
      - name: check out repo
        uses: actions/checkout@v4
      - name: set up node js version
        uses:  actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        uses: npm install
      - name: unit testing
        uses: npm test
        